version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/phonebook_production
      - PGUSER=postgres
      - PGPASSWORD=postgres
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phonebook_production
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
